platform :ios, '11.0' # Set to 11 to enable latest Google maps sdk

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

end
